title = "Devansh Tanna"

theme = "emily_zola_theme"

# The URL the site will be built for
base_url = "https://devansh0210.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    {name = "categories", rss = false},
    {name = "tags", rss = false},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
      
[extra]
# Put all your custom variables here
# Image of your avatar displayed on the landing page
emily_author = "Devansh Tanna"

# Path to the header icon / favicon image.
# Please save image to static/images
emily_icon = "/images/logo.png"

emily_favicon = "/images/favicon.png"

# header icon width.
# height will be automatically rendered.
emily_iconsize = 70

# number of posts in index.html.
emily_indexposts = 5

# switch to dark-theme
emily_dark_mode = true

# show theme-toggler
emily_theme_toggler = true